#!/usr/bin/env bash
# Fizzbuzz


for ((number = 1; number <= 100; number++)); do


  if ! (( number % 3 )) && ! (( number % 5 )); then
    echo "FizzBuzz"
  elif ! (( number % 3 )); then
    echo "Fizz"
  elif ! (( number % 5 )); then
    echo "Buzz"
  else
    echo "$number"
  fi
  
done
