#!/usr/bin/env bash
#A Bash script that displays the content of the file /etc/passwd in a specifc format.

#Password file path
pass="/etc/passwd"

#setting the internal field seprator to Null
# read -r treats the \ as a normal char
while IFS= read -r line; do
  USERNAME=$(echo "$line" | cut -d ':' -f 1)
  GROUP_ID=$(echo "$line" | cut -d ':' -f 4)
  HOME_DIRECTORY=$(echo "$line" | cut -d ':' -f 6)
  SHEL=$(echo "$line" | cut -d ':' -f 7)
  USER_ID=$(echo "$line" | cut -d ':' -f 3)
  PASSWORD=$(echo "$line" | cut -d ':' -f 2)
  USER_ID_INFO=$(echo "$line" | cut -d ':' -f 5)
 
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHEL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "$pass"

